### ISSUE TITLE
Change cursor on Mac when inside splitter

### ISSUE THREAD

**Issue by benagarr** [stevengharris/SplitView#7]
Hey, I think it wold be really cool if you could get the same cursor on Mac in this that you get in the finder or Xcode when hovering over the splitter.

Maybe I can dig in and figure it out, but am new to Swift UI so wanted to ask about it.  Maybe it's simple somehow?

Thanks!

**Comment by stevengharris** [comment]
If you look in Sources/SplitView/Splitter.swift you will see some commented-out code I was using for a while on Mac Catalyst. 

```
/*
 TODO: This seems to work okay in simple situations, but is kinda janky in others, so removing for now
.onHover { inside in
 // Perhaps should consider some kind of custom hoverEffect, since the cursor change
 // doesn't work on iOS
    #if targetEnvironment(macCatalyst)
    if inside {
        layout.isHorizontal ? NSCursor.resizeLeftRight.push() : NSCursor.resizeUpDown.push()
    } else {
        NSCursor.pop()
    }
    #endif
}
*/
```

There might be a good SwiftUI way to do this now, but in the version I was using at the time I had to resort to NSCursor. I don't remember exactly what the jankiness I referred to in the TODO comment was. I think it was that the cursor didn't change properly back to normal in some conditions. Hopefully it works okay or will put you on the right path. Happy to take a pull request if you like your result, but in any case, please let me know what worked for you. Thanks!

**Comment by benagarr** [comment]
I'll try this out and tell you how it goes.  Thanks Steven

**Comment by aehlke** [comment]
please share any progress using NSCursor because native without catalyst is still great to have, thanks

**Comment by stevengharris** [comment]
The changes in https://github.com/stevengharris/SplitView/pull/16 will add native cursor changes for Mac Catalyst and MacOS. The jankiness I found earlier when I went back to look at this in more detail was all around nested split views. I was not popping the cursor unless `onHover` was triggered and the cursor was outside of the Splitter. I believe the right thing to do is to always pop the cursor, and this is particularly needed when you transition from one splitter to another when using nested split views. 

I can still detect some issues when you *carefully* drag your cursor along a splitter and move to another splitter when you have them nested. This is possible to see in the "Nested adjustable" demo. What happens is that occasionally the `onHover` in the splitter you're moving into is just not triggered as you transition from one splitter to the next. However, since the resizing cursor has been popped as it exits from the first splitter, the cursor will just be the normal arrow style and not transition to the different resizing style. It's pretty difficult to cause this to occur, and as a result, I just don't think I'm going to care about it happening very infrequently. And since the cause is that the `onHover` is not being triggered when the cursor transitions from one splitter to another in the nested case, I really don't know what I could do about it anyway. It's possible that [continuousOnHover](https://nilcoalescing.com/blog/TrackingHoverLocationInSwiftUI/) would avoid the problem, but frankly it's a mess to sort out how to deal with the version dependencies to use it, and I don't want to foist a required version change on people consuming the library.

I updated the `DemoSplitter` used in the "Custom splitter" demo to show how to avoid having the resizing cursor change take place when hovering over embedded content in a custom splitter, too.
